version: "3.9"
services:
    frontend:
        build: frontend
        volumes:
            - ./frontend:/app
        ports:
            - "8000:3000"
    backend:
        build: backend
        volumes:
            - ./backend:/app
        ports:
            - "8001:3000"
    database:
        image: "mysql:8"
        restart: always
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        ports:
            - "8002:3306"
        environment:
            MYSQL_ROOT_PASSWORD: perlego
            MYSQL_USER: perlego
            MYSQL_PASSWORD: perlego
            MYSQL_DATABASE: perlego

